mutation CreateContactWaGroup($input: ContactWaGroupInput!) {
  createContactWaGroup(input: $input) {
    contactWaGroup {
      id
      value
      contact {
        id
      }
    }
    errors {
      key
      message
    }
  }
}
