fragment ContactWaGroupFields on ContactWaGroupResult {
  contactWaGroup {
    contact {
      id
      name
      phone
    }
    waGroups {
      id
      label
    }
    id
  }
  errors {
    key
    message
  }
}
