fragment ContactWaGroupFields on ContactWaGroupResult {
  contactWaGroup {
    contact {
      id
      waGroups {
        id
        label
      }
    }
    id
  }
  errors {
    key
    message
  }
}
