fragment ContactWaGroupFields on ContactWaGroupResult {
  contact_wa_group {
      contact {
        groups {
          id
        }
        id
        name
      }
      id
    }
  }


fragment ErrorFields on ContactWaGroupResult {
  errors {
    key
    message
  }
}