mutation SetPrimaryPhone($waGroupId: ID!, $waManagedPhoneId: ID!) {
  setPrimaryPhone(waGroupId: $waGroupId, waManagedPhoneId: $waManagedPhoneId) {
    primaryPhone {
      id
      isPrimary
      isActive
      waManagedPhone {
        id
        phone
      }
    }
    warning
    errors {
      key
      message
    }
  }
}
