mutation UpdateWaGroupContacts($input: WaGroupContactsInput!) {
  updateWaGroupContacts(input: $input) {
    numberDeleted
    waGroupContacts {
      contact {
        id
      }
      id
    }
  }
}
