mutation UpdateContactWaGroups($input: UpdateContactWaGroupsInput!) {
  updateContactWaGroups(input: $input) {
    waGroupContacts {
      contact {
        id
      }
      id
    }
    numberDeleted
  }
}
