mutation updateContactWaGroups($input: WaGroupContactsInput!) {
  updateContactWaGroups(input: $input) {
    numberDeleted
    waGroupContacts {
      contact {
        id
      }
      id
    }
  }
}
