defmodule Glific.AI.Codec do
  @moduledoc """
  Encodes and decodes a single `ReqLLM.Message` to and from a jsonb-safe map.

  `ReqLLM` derives `Jason.Encoder` on its structs but ships no decoder, and its structs are
  generated by `Zoi.Struct.struct_fields/1`, so field order and presence can move between minor
  versions. This module owns the only persisted representation of conversation history; nothing
  else may write `ai_messages.parts`.

  Three shapes carry data that must survive a round trip, and only one of them lives in
  `content`:

    * `content` — a list of `ReqLLM.Message.ContentPart`
    * `tool_calls` — a list of `ReqLLM.ToolCall`, a sibling field, not a content part
    * `reasoning_details` — where the thinking `signature` lives. Losing it makes the next
      Anthropic turn fail, and the loss is invisible until then.

  An unrecognised content type or role is an error, never a silent drop: dropping a tool call
  desynchronises the call/result pairing and the provider rejects the whole context.

  ## Canonical form

  JSON cannot represent the difference between an atom key and a string key, so a message that
  has been to storage and back is not always `==` to the one that came off the wire. Rather than
  paper over that at decode time, every message is normalised **on the way in**, so the in-memory
  form is the one storage will hand back:

    * free-form maps — `metadata`, `provider_data` — carry **string** keys
    * `ToolCall.function` carries **atom** keys for `name`, `arguments` and `builtin?`, because
      ReqLLM's own encoder and inspector reach for them with dot access
    * enum-like atoms — `role`, content `type`, reasoning `provider` — stay atoms and are
      restored from a closed whitelist

  `normalize/1` is idempotent, and the contract is `decode(encode(m)) == normalize(m)` for every
  message. Call it once on anything arriving from a provider; after that, stored and in-memory
  representations cannot drift.
  """

  alias ReqLLM.Message
  alias ReqLLM.Message.ContentPart
  alias ReqLLM.Message.ReasoningDetails
  alias ReqLLM.ToolCall

  @codec_version 1

  @roles %{user: "user", assistant: "assistant", system: "system", tool: "tool"}
  @roles_inverse Map.new(@roles, fn {atom, string} -> {string, atom} end)

  @part_types %{
    text: "text",
    image_url: "image_url",
    video_url: "video_url",
    image: "image",
    file: "file",
    thinking: "thinking"
  }
  @part_types_inverse Map.new(@part_types, fn {atom, string} -> {string, atom} end)

  @providers %{
    anthropic: "anthropic",
    google: "google",
    openai: "openai",
    openrouter: "openrouter"
  }
  @providers_inverse Map.new(@providers, fn {atom, string} -> {string, atom} end)

  @doc "The codec version stamped onto every encoded message."
  @spec version() :: pos_integer()
  def version, do: @codec_version

  @doc """
  Canonicalises a message so its in-memory form matches what storage returns.

  Idempotent. Call it on every message arriving from a provider, before it is stored or compared.
  """
  @spec normalize(Message.t()) :: Message.t()
  def normalize(%Message{} = message) do
    %Message{
      message
      | content: Enum.map(message.content, &normalize_part/1),
        metadata: stringify(message.metadata),
        tool_calls: normalize_tool_calls(message.tool_calls),
        reasoning_details: normalize_reasoning(message.reasoning_details)
    }
  end

  @doc "Encodes one message into a jsonb-safe map. Normalises first, so encoding is canonical."
  @spec encode(Message.t()) :: {:ok, map()} | {:error, term()}
  def encode(%Message{} = message) do
    message = normalize(message)

    with {:ok, role} <- encode_role(message.role),
         {:ok, content} <- map_while_ok(message.content, &encode_part/1) do
      {:ok,
       %{
         "v" => @codec_version,
         "req_llm" => req_llm_version(),
         "role" => role,
         "content" => content,
         "name" => message.name,
         "tool_call_id" => message.tool_call_id,
         "tool_calls" => encode_tool_calls(message.tool_calls),
         "metadata" => stringify(message.metadata),
         "reasoning" => encode_reasoning(message.reasoning_details)
       }}
    end
  end

  def encode(other), do: {:error, {:not_a_message, other}}

  @doc "Decodes a map produced by `encode/1` back into a message."
  @spec decode(map()) :: {:ok, Message.t()} | {:error, term()}
  def decode(%{"v" => @codec_version} = map) do
    with {:ok, role} <- decode_role(map["role"]),
         {:ok, content} <- map_while_ok(map["content"] || [], &decode_part/1),
         {:ok, tool_calls} <- decode_tool_calls(map["tool_calls"]),
         {:ok, reasoning} <- decode_reasoning(map["reasoning"]) do
      {:ok,
       %Message{
         role: role,
         content: content,
         name: map["name"],
         tool_call_id: map["tool_call_id"],
         tool_calls: tool_calls,
         metadata: map["metadata"] || %{},
         reasoning_details: reasoning
       }}
    end
  end

  def decode(%{"v" => other}), do: {:error, {:unsupported_version, other}}
  def decode(_map), do: {:error, :missing_version}

  @spec req_llm_version() :: String.t()
  defp req_llm_version do
    case :application.get_key(:req_llm, :vsn) do
      {:ok, vsn} -> List.to_string(vsn)
      _undefined -> "unknown"
    end
  end

  @spec encode_role(atom()) :: {:ok, String.t()} | {:error, term()}
  defp encode_role(role) do
    case Map.fetch(@roles, role) do
      {:ok, string} -> {:ok, string}
      :error -> {:error, {:unknown_role, role}}
    end
  end

  @spec decode_role(term()) :: {:ok, atom()} | {:error, term()}
  defp decode_role(role) do
    case Map.fetch(@roles_inverse, role) do
      {:ok, atom} -> {:ok, atom}
      :error -> {:error, {:unknown_role, role}}
    end
  end

  @spec encode_part(ContentPart.t()) :: {:ok, map()} | {:error, term()}
  defp encode_part(%ContentPart{} = part) do
    case Map.fetch(@part_types, part.type) do
      {:ok, type} ->
        {:ok,
         %{
           "t" => type,
           "text" => part.text,
           "url" => part.url,
           "data" => encode_binary(part.data),
           "file_id" => part.file_id,
           "media_type" => part.media_type,
           "filename" => part.filename,
           "metadata" => stringify(part.metadata)
         }}

      :error ->
        {:error, {:unknown_part_type, part.type}}
    end
  end

  defp encode_part(other), do: {:error, {:not_a_content_part, other}}

  @spec decode_part(map()) :: {:ok, ContentPart.t()} | {:error, term()}
  defp decode_part(%{"t" => type} = map) do
    case Map.fetch(@part_types_inverse, type) do
      {:ok, atom} ->
        {:ok,
         %ContentPart{
           type: atom,
           text: map["text"],
           url: map["url"],
           data: decode_binary(map["data"]),
           file_id: map["file_id"],
           media_type: map["media_type"],
           filename: map["filename"],
           metadata: map["metadata"] || %{}
         }}

      :error ->
        {:error, {:unknown_part_type, type}}
    end
  end

  defp decode_part(other), do: {:error, {:malformed_part, other}}

  @spec encode_tool_calls([ToolCall.t()] | nil) :: [map()] | nil
  defp encode_tool_calls(nil), do: nil

  defp encode_tool_calls(calls) when is_list(calls) do
    Enum.map(calls, fn %ToolCall{} = call ->
      %{"id" => call.id, "type" => call.type, "function" => stringify(call.function)}
    end)
  end

  @spec decode_tool_calls(term()) :: {:ok, [ToolCall.t()] | nil} | {:error, term()}
  defp decode_tool_calls(nil), do: {:ok, nil}

  defp decode_tool_calls(calls) when is_list(calls) do
    map_while_ok(calls, fn
      %{"id" => id, "function" => function} = call ->
        {:ok,
         %ToolCall{
           id: id,
           type: call["type"] || "function",
           function: canonical_function(function)
         }}

      other ->
        {:error, {:malformed_tool_call, other}}
    end)
  end

  defp decode_tool_calls(other), do: {:error, {:malformed_tool_calls, other}}

  # ReqLLM's own Jason.Encoder and Inspect for ToolCall reach into `function.name` and
  # `function.arguments` with dot access, so a string-keyed map raises KeyError the next time the
  # context is sent to a provider — one turn after the data was written, with nothing wrong at
  # write time. These keys are therefore canonically atoms, everywhere.
  @function_keys %{"name" => :name, "arguments" => :arguments, "builtin?" => :builtin?}

  @spec canonical_function(term()) :: term()
  defp canonical_function(function) when is_map(function) do
    Map.new(function, fn {key, value} -> {canonical_function_key(key), stringify(value)} end)
  end

  defp canonical_function(function), do: function

  @spec canonical_function_key(term()) :: atom() | String.t()
  defp canonical_function_key(key) do
    string = to_string(key)
    Map.get(@function_keys, string, string)
  end

  @spec normalize_part(term()) :: term()
  defp normalize_part(%ContentPart{} = part) do
    %ContentPart{part | metadata: stringify(part.metadata)}
  end

  defp normalize_part(other), do: other

  @spec normalize_tool_calls([ToolCall.t()] | nil) :: [ToolCall.t()] | nil
  defp normalize_tool_calls(nil), do: nil

  defp normalize_tool_calls(calls) when is_list(calls) do
    Enum.map(calls, fn
      %ToolCall{} = call ->
        %ToolCall{
          call
          | type: call.type || "function",
            function: canonical_function(call.function)
        }

      other ->
        other
    end)
  end

  @spec normalize_reasoning([ReasoningDetails.t()] | nil) :: [ReasoningDetails.t()] | nil
  defp normalize_reasoning(nil), do: nil

  defp normalize_reasoning(details) when is_list(details) do
    Enum.map(details, fn
      %ReasoningDetails{} = detail ->
        %ReasoningDetails{
          detail
          | encrypted?: detail.encrypted? || false,
            index: detail.index || 0,
            provider: if(Map.has_key?(@providers, detail.provider), do: detail.provider),
            provider_data: stringify(detail.provider_data)
        }

      other ->
        other
    end)
  end

  @spec encode_reasoning([ReasoningDetails.t()] | nil) :: [map()] | nil
  defp encode_reasoning(nil), do: nil

  defp encode_reasoning(details) when is_list(details) do
    Enum.map(details, fn %ReasoningDetails{} = detail ->
      %{
        "text" => detail.text,
        "signature" => detail.signature,
        "encrypted" => detail.encrypted?,
        "provider" => Map.get(@providers, detail.provider),
        "format" => detail.format,
        "index" => detail.index,
        "provider_data" => stringify(detail.provider_data)
      }
    end)
  end

  @spec decode_reasoning(term()) :: {:ok, [ReasoningDetails.t()] | nil} | {:error, term()}
  defp decode_reasoning(nil), do: {:ok, nil}

  defp decode_reasoning(details) when is_list(details) do
    map_while_ok(details, fn detail ->
      {:ok,
       %ReasoningDetails{
         text: detail["text"],
         signature: detail["signature"],
         encrypted?: detail["encrypted"] || false,
         provider: Map.get(@providers_inverse, detail["provider"]),
         format: detail["format"],
         index: detail["index"] || 0,
         provider_data: detail["provider_data"] || %{}
       }}
    end)
  end

  defp decode_reasoning(other), do: {:error, {:malformed_reasoning, other}}

  # Attachment bytes are frequently not valid UTF-8, which jsonb rejects outright.
  @spec encode_binary(term()) :: term()
  defp encode_binary(data) when is_binary(data) do
    if String.valid?(data), do: data, else: %{"b64" => Base.encode64(data)}
  end

  defp encode_binary(data), do: data

  @spec decode_binary(term()) :: term()
  defp decode_binary(%{"b64" => encoded}), do: Base.decode64!(encoded)
  defp decode_binary(data), do: data

  @spec stringify(term()) :: term()
  defp stringify(map) when is_map(map) and not is_struct(map) do
    Map.new(map, fn {key, value} -> {to_string(key), stringify(value)} end)
  end

  defp stringify(list) when is_list(list), do: Enum.map(list, &stringify/1)

  defp stringify(atom) when is_atom(atom) and not is_boolean(atom) and not is_nil(atom),
    do: to_string(atom)

  defp stringify(other), do: other

  @spec map_while_ok([term()], (term() -> {:ok, term()} | {:error, term()})) ::
          {:ok, [term()]} | {:error, term()}
  defp map_while_ok(list, fun) do
    list
    |> Enum.reduce_while({:ok, []}, fn item, {:ok, acc} ->
      case fun.(item) do
        {:ok, value} -> {:cont, {:ok, [value | acc]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, acc} -> {:ok, Enum.reverse(acc)}
      error -> error
    end
  end
end
