query whatsapp_phone_screen($wa_managed_phone_id: ID!) {
  whatsapp_phone_screen(wa_managed_phone_id: $wa_managed_phone_id) {
    wa_phone_screen {
      code
      status
      expires_at
    }
    errors {
      key
      message
    }
  }
}
