fragment TicketFields on TicketResult {
  ticket {
    id
    body
    topic
    status
    remarks
    messageNumber
    contact {
      id
      name
      phone
    }
    user {
      id
      name
      phone
    }
  }
}

fragment ErrorFields on TicketResult {
  errors {
    key
    message
  }
}
