mutation startContactFlow($flowId: ID!, $contactId: ID!, $channel: MessageChannelEnum) {
  startContactFlow(flowId: $flowId, contactId: $contactId, channel: $channel) {
  	success
  	errors {
    	key
  		message
  	}
  }
}
