fragment FlowFields on FlowResult {
  flow {
    id
    name
    keywords
    flowType
    channels
    isBackground
    isPinned
    isTemplate
  }
}

fragment ErrorFields on FlowResult {
  errors {
    key
    message
  }
}