mutation updateWaGroupSubject($id: ID!, $waManagedPhoneId: ID!, $subject: String!) {
  updateWaGroupSubject(id: $id, waManagedPhoneId: $waManagedPhoneId, subject: $subject) {
    waGroup {
      id
      label
      bspId
    }
    errors {
      key
      message
    }
  }
}
