mutation updateWaGroup($input: UpdateWaGroupInput!) {
  updateWaGroup(input: $input) {
    waGroup {
      id
      label
      bspId
      lastCommunicationAt
      primaryPhone {
        id
        phone
        label
      }
      phones {
        id
        isPrimary
        isActive
        waManagedPhone {
          id
          phone
        }
      }
      contacts {
        id
        name
        phone
      }
    }
    errors {
      key
      message
    }
  }
}
