version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "elixir"
    commit-message:
      prefix: "chore(deps)"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
