#import "./fields.frag.gql"

mutation SaveWhatsappFormRevision($input: WhatsappFormRevisionInput!) {
  saveWhatsappFormRevision(input: $input) {
    ...WhatsappFormRevisionFields
    ...WhatsappFormRevisionsErrorFields
  }
}
