#import "./fields.frag.gql"

query WhatsappFormRevision($whatsappFormRevisionId: ID!) {
  whatsappFormRevision(id: $whatsappFormRevisionId) {
    ...WhatsappFormRevisionFields
    ...WhatsappFormRevisionsErrorFields
  }
}
