fragment TriggerFields on TriggerResult {
  trigger {
    id
    start_at
    end_date
    name
    frequency
    next_trigger_at
    flow {
      id
      name
    }
    groups
  }
}

fragment ErrorFields on TriggerResult {
  errors {
    key
    message
  }
}
