query triggers($filter: triggerFilter, $opts: Opts) {
  triggers(filter: $filter, opts: $opts) {
    id
    start_at
    end_date
    flow {
      id
      name
    }
    group {
      id
      label
    }
  }
}
