mutation createTag($input:TagInput!) {
  createTag(input: $input) {
    tag {
      id
      label
      language {
        id
        label
      }
    }
    errors {
      key
      message
    }
  }
}