fragment TagFields on TagResult {
  tag {
    id
    label
    keywords

    language {
      id
      label
      locale
    }
  }
}

fragment ErrorFields on TagResult {
  errors {
    key
    message
  }
}