query tags($filter: TagFilter, $order: SortOrder, $limit: Int, $offset: Int) {
  tags(filter: $filter, order: $order, limit: $limit, offset: $offset) {
    id
    label
    language {
      id
      label
    }
  }
}
