mutation UpdateWaGroupCollection($input: UpdateWaGroupsCollectionInput!) {
  updateWaGroupCollection(input: $input) {
    collectionWaGroups {
      group {
        id
        label
        waGroups {
          id
          label
        }
      }
      id
    }
    waGroupsDeleted
  }
}
