fragment ProviderFields on ProviderResult {
  provider {
    id
    name
    group
    description
    shortcode
    keys
    secrets
  }
}

fragment ErrorFields on ProviderResult {
  errors {
    key
    message
  }
}