fragment AssistantFields on AssistantResult {
  assistant {
    id
    name
    assistant_id
    temperature
    effort
    settings
    status
    new_version_in_progress
    last_evaluation_summary
    vector_store {
      id
      knowledge_base_version_id
      name
      status
      legacy
      size
      files {
        id
        name
        uploaded_at
      }
    }
    inserted_at
    updated_at
  }
}

fragment ErrorFields on AssistantResult {
  errors {
    key
    message
  }
}
