fragment AssistantFields on AssistantResult {
  assistant {
    id
    name
    assistant_id
    temperature
    status
    new_version_in_progress
    vector_store {
      id
      vector_store_id
      name
      status
      legacy
      size
      files {
        id
        name
        uploaded_at
      }
    }
    inserted_at
    updated_at
  }
}

fragment ErrorFields on AssistantResult {
  errors {
    key
    message
  }
}
