#import "./knowledge_base_fields.frag.gql"

mutation create_knowledge_base($media_info: [FileInfoInput!]!, $id: ID) {
    create_knowledge_base(media_info: $media_info, id: $id) {
        knowledge_base {
            id
            vector_store_id
            name
            status
            size
            inserted_at
            updated_at
        }
        ...ErrorFields
    }
}
