mutation add_assistant_files($media_info: [FileInfoInput!]!, $id: ID) {
    add_assistant_files(media_info: $media_info, id: $id) {
        knowledge_base {
            id
            vector_store_id
            name
            status
            size
            inserted_at
            updated_at
        }
        errors {
            key
            message
        }
    }
}
