query Assistants($filter: AssistantFilter, $opts: Opts) {
  Assistants(filter: $filter, opts: $opts) {
    id
    name
    assistant_id
    temperature
    effort
    settings
    status
    new_version_in_progress
    live_version_number
    last_evaluation_summary
    vector_store {
      id
      knowledge_base_version_id
      name
      status
      legacy
      files {
        id
        name
        uploaded_at
      }
    }
    inserted_at
    updated_at
  }
}
