query AssistantConfigVersions {
  assistantConfigVersions {
    id
    assistantId
    kaapiUuid
    versionNumber
    description
    prompt
    provider
    model
    settings
    status
    failureReason
    insertedAt
    updatedAt
  }
}
