subscription assistantConfigVersionUpdated {
  assistantConfigVersionUpdated {
    id
    versionLabel
    model
    prompt
    settings
    status
    description
    insertedAt
    updatedAt
  }
}

subscription knowledgeBaseVersionUpdated {
  knowledgeBaseVersionUpdated {
    id
    knowledgeBaseId
    versionNumber
    status
    size
    insertedAt
    updatedAt
  }
}
