subscription assistantConfigVersionUpdated {
  assistantConfigVersionUpdated {
    id
    versionNumber
    model
    prompt
    settings
    status
    isLive
    description
    insertedAt
    updatedAt
  }
}

subscription knowledgeBaseVersionUpdated {
  knowledgeBaseVersionUpdated {
    id
    knowledgeBaseId
    versionNumber
    status
    size
    insertedAt
    updatedAt
  }
}
