mutation updateLanguage($id: ID!, $input: LanguageInput!) {
  updateLanguage(id: $id, input: $input) {
    language {
      id
      label
      locale
    }
    errors {
      key
      message
    }
  }
}