fragment ConsultingHourFields on ConsultingHourResult {
  consultingHour {
    participants
    organization_id
    organization_name
    staff
    content
    when
    duration
    is_billable
    organization {
      name
      shortcode
    }
  }
}

fragment ErrorFields on ConsultingHourResult {
  errors {
    key
    message
  }
}
