query ConsultingHours($filter: ConsultingHourFilter, $opts: Opts) {
  ConsultingHours(filter: $filter, opts: $opts) {
    participants
    organizationName
    staff
    content
    when
    duration
    organization {
      name
      shortcode
    }
  }
}
