#import "./fields.frag.gql"

mutation updateConsultingHour($id: ID!, $input: ConsultingHourInput!) {
  updateConsultingHour(id: $id, input: $input) {
    ...ConsultingHourFields

    ...ErrorFields
  }
}
