fragment ContactsFieldFields on ContactsFieldResult {
  consultingHour {
    id
    name
    scope
    shortcode
    valueType
    insertedAt
    updatedAt
    organization {
      isActive
      name
      shortcode
    }
  }
}

fragment ErrorFields on ContactsFieldResult {
  errors {
    key
    message
  }
}
