query consultingHours($filter: ContactsFieldFilter, $opts: Opts) {
  consultingHours(filter: $filter, opts: $opts) {
    id
    participants
    organizationName
    staff
    content
    when
    duration
    isBillable
  }
}
