#import "./fields.frag.gql"

mutation updateContactsField($id: ID!, $input: ContactsFieldInput!) {
  updateContactsField(id: $id, input: $input) {
    ...ContactsFieldFields

    ...ErrorFields
  }
}
