query search($term: String!, $shouldSave: Boolean!, $saveSearchLabel: String!) {
  search(term: $term, saveSearch: $shouldSave, saveSearchLabel: $saveSearchLabel) {
    contact {
      id
      name
      phone
    }
    messages {
      id
      body
      flow
      type
    }
  }
}
