query waSearch(
    $waGroupOpts: Opts!,
    $waMessageOpts: Opts!
  ) {
    waSearch(waGroupOpts: $waGroupOpts, waMessageOpts: $waMessageOpts) {
        wa_group {
            id
            label
            bsp_id
            last_communication_at
        }
        wa_messages {
            id
            body
            flow
            type
            contact {
                id
                name
                phone
            }
      }
    }
}
