fragment CredentialFields on CredentialResult {
  credential {
    id
    provider {
      shortcode
    }
    keys
    secrets
    isActive
  }
}

fragment ErrorFields on CredentialResult {
  errors {
    key
    message
  }
}