fragment TemplateTagFields on TemplateTagResult {
  template_tag {
    id
   
    template {
      id
      label
    }

    tag {
      id
      label
    }
  }
}

fragment ErrorFields on TemplateTagResult {
  errors {
    key
    message
  }
}