fragment GroupFields on GroupResult {
  group {
    id
    label
    is_restricted
    contacts {
      id
      name
    }
    users {
      id
      name
    }
  }
}

fragment ErrorFields on GroupResult {
  errors {
    key
    message
  }
}