#import "./fields.frag.gql"

mutation createTemplateFormMessage($messageId: ID!, $input: MessageToTemplateInput!) {
  createTemplateFormMessage(messageId: $messageId, input: $input ) {
    ...SessionTemplateFields
    ...ErrorFields
  }
}
