fragment SessionTemplateFields on SessionTemplateResult {
  sessionTemplate {
    id
    label
    body
    translations

    language {
      id
      label
      locale
    }
  }
}

fragment ErrorFields on SessionTemplateResult {
  errors {
    key
    message
  }
}