fragment SessionTemplateFields on SessionTemplateResult {
  sessionTemplate {
    id
    label
    body
    type
    shortcode
    is_hsm
    category
    example
    is_reserved
    is_active
    has_buttons
    button_type
    buttons
    language {
      id
      label
      locale
    }
  }
}

fragment ErrorFields on SessionTemplateResult {
  errors {
    key
    message
  }
}
