query groupedHsmTemplates($filter: SessionTemplateFilter, $opts: Opts) {
  groupedHsmTemplates(filter: $filter, opts: $opts) {
    shortcode
    label
    category
    tag {
      id
      label
    }
    languageVariants {
      id
      bspId
      body
      category
      language {
        id
        label
      }
      status
      quality
      reason
      updatedAt
      isActive
    }
  }
}
