#import "./fields.frag.gql"

mutation reapplySessionTemplate($id: ID!, $input: SessionTemplateInput!) {
  reapplySessionTemplate(id: $id, input: $input) {
    ...SessionTemplateFields

    ...ErrorFields
  }
}
