mutation rewriteTemplateForUtility($body: String!, $footer: String, $buttons: [String], $label: String) {
  rewriteTemplateForUtility(body: $body, footer: $footer, buttons: $buttons, label: $label) {
    body
    suggestedCategory
    changes {
      whatChanged
      why
      bestPractice
      bestPracticeUrl
    }
    errors {
      key
      message
    }
  }
}
