query templateLibrary($filter: TemplateLibraryFilter) {
  templateLibrary(filter: $filter) {
    elementName
    category
    body
    languageCode
    industry
    topic
    usecase
    containerMeta
  }
}
