name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Step by step guide to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      placeholder: "Ex: Pop up should open on button click"
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      placeholder: "Ex: Pop up did not open"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Points to verify the bug is fixed
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach screenshots or screenrecords
    validations:
      required: false
