name: Feature Request
description: Submit a feature request.
title: "[Feature]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      placeholder: "Ex: User should be able to create a flow"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Points to verify the feature is working as per requirements
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach screenshots or screenrecords
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional info or context required to work on the feature
    validations:
      required: false
