mutation createMessageTags($input:MessageTagsInput!) {
  createMessageTags(input: $input) {
    messageTags {
      id
      message {
        id
        body
      }
      tag {
        id
        label
      }
      value
    }
  }
}