#import "./fields.frag.gql"

mutation updateOrganizationExtension($clientId: ID!, $input: ExtensionInput!) {
  updateOrganizationExtension(clientId: $clientId, input: $input) {
    ...ExtensionFields

    ...ErrorFields
  }
}