#import "./fields.frag.gql"

mutation copyInteractiveTemplate($id: ID!, $input: InteractiveTemplateInput!) {
  copyInteractiveTemplate(id: $id, input: $input) {
    ...InteractiveTemplateFields

    ...ErrorFields
  }
}