#import "./fields.frag.gql"

mutation createInteractiveTemplate($input: InteractiveTemplateInput!) {
  createInteractiveTemplate(input: $input) {
    ...InteractiveTemplateFields

    ...ErrorFields
  }
}