fragment InteractiveFields on InteractiveResult {
interactive {
    insertedAt
    interactiveContent
    label
    type
    updatedAt
    id
  }
}

fragment ErrorFields on InteractiveResult {
  errors {
    key
    message
  }
}
