query interactiveTemplates($filter: InteractiveTemplateFilter, $opts: Opts) {
  interactiveTemplates(filter: $filter, opts: $opts) {
    insertedAt
    interactiveContent
    label
    type
    updatedAt
    id
  }
}
