#import "./fields.frag.gql"

mutation updateInteractiveTemplate($id: ID!, $input: InteractiveTemplateInput!) {
  updateInteractiveTemplate(id: $id, input: $input) {
    ...InteractiveTemplateFields

    ...ErrorFields
  }
}