mutation updateGroupUsers($input:GroupUsersInput!) {
  updateGroupUsers(input: $input) {
    groupUsers {
      id
      user {
        id
        name
      }
      group {
        id
        label
      }
    }
    numberDeleted
  }
}