query ContactHistory($filter: ContactsHistoryFilter, $opts: Opts) {
  contactHistory(filter: $filter, opts: $opts) {
    eventDatetime
    eventLabel
    eventMeta
    eventType
    id
    insertedAt
    updatedAt
  }
}
