fragment ContactFields on ContactResult {
  contact {
    id
    name
    phone
    maskedPhone
    fields
    settings
    active_profile {
      id
    }
    language {
      id
    }
  }
}

fragment ErrorFields on ContactResult {
  errors {
    key
    message
  }
}