#import "./ImportFields.frag.gql"

mutation importContacts($data : String!, $type : ImportContactsTypeEnum, $group_label: String!) {
  importContacts(data: $data, type: $type, group_label: $group_label) {
      status

      ...ImportErrors
  }
}