#import "./ImportFields.frag.gql"

mutation importContacts($data : String!, $type : ImportContactsTypeEnum, $id: ID!) {
  importContacts(data: $data, type: $type, id: $id) {
      status

      ...ImportErrors
  }
}