query searchConversation($term: String!) {
  searchConversation(term: $term) {
    contact {
      id
      name
      phone
    }
    messages {
      id
      body
      flow
      type
    }
  }
}
