mutation updateContact($id: ID!, $input: ContactInput!) {
  updateContact(id: $id, input: $input) {
    contact {
      id
      name
      phone
    }
    errors {
      key
      message
    }
  }
}