#import "./fields.frag.gql"

mutation updateUser($id: ID!, $input: CurrentInput!, $groupIds:[ID]!) {
  updateUser(id: $id, input: $input, groupIds: $groupIds) {
    ...UserFields

    ...ErrorFields
  }
}