fragment VectorStoreFields on VectorStoreResult {
  vectorStore {
    name
    vector_store_id
    files {
      id
      info {
        id
      }
    }
  }
}

fragment ErrorFields on VectorStoreResult {
  errors {
    key
    message
  }
}
