fragment VectorStoreFields on VectorStoreResult {
  vectorStore {
    id
    name
    vector_store_id
    files {
      id
      info {
        id
      }
    }
    assistants {
      id
      name
    }
  }
}

fragment ErrorFields on VectorStoreResult {
  errors {
    key
    message
  }
}
