fragment UnifiedAssistantFields on UnifiedAssistantResult {
  assistant {
    id
    name
    assistant_id
    temperature
    status
    new_version_in_progress
    vector_store {
      id
      llm_service_id
      name
      status
      legacy
      size
      files {
        id
        name
        uploaded_at
      }
    }
    inserted_at
    updated_at
  }
}

fragment UnifiedErrorFields on UnifiedAssistantResult {
  errors {
    key
    message
  }
}
