mutation createAndSendMessageToContacts($input:MessageInput!, $contact_ids: [ID]!) {
  createAndSendMessageToContacts(input: $input, contact_ids: $contact_ids) {
    id
    body
    sender {
      id
      name
    }

    receiver {
      id
      name
    }
  }
}
