fragment MessageFields on MessageResult {
  message {
    id
    body

    sender {
      id
      name
    }

    receiver {
      id
      name
    }
  }
}

fragment ErrorFields on MessageResult {
  errors {
    key
    message
  }
}