query messages ($filter: MessageFilter, $opts: Opts) {
  messages (filter: $filter, opts: $opts) {
    id
    body
    sender {
      id
      name
    }

    receiver {
      id
      name
    }
  }
}