fragment WhatsappFormFields on WhatsappFormResult {
  whatsappForm {
    id
    name
    status
    categories
    definition
    description
    metaFlowId
    sheetId
    sheet {
      id
      url
    }
    insertedAt
    updatedAt
  }
}

fragment WhatsappFormErrorFields on WhatsappFormResult {
  errors {
    key
    message
  }
}
