fragment WhatsappFormFields on WhatsappFormResult {
  whatsappForm {
    id
    name
    status
    categories
    description
    metaFlowId
    insertedAt
    updatedAt
  }
}

fragment WhatsappFormErrorFields on WhatsappFormResult {
  errors {
    key
    message
  }
}
