query list_whatsapp_forms($filter: WhatsappFormFilter) {
  listWhatsappForms(filter: $filter) {
    id
    name
    status
    description
    metaFlowId
    categories
    sheet {
      id
      label
      url
      isActive
      sheetDataCount
    }
  }
}
