query improvePrompt($evaluationId: ID!) {
  improvePrompt(evaluationId: $evaluationId) {
    improvePrompt {
      status
      recommendedPrompt
      commitMessage
      assistantConfigVersionId
      versionNumber
      failureReason
    }
    errors {
      message
    }
  }
}
