mutation deleteOnboardedOrganization($input:DeleteOrganizationInput!) {
  deleteOnboardedOrganization(input: $input) {
    organization {
      email
      id
      isApproved
      isActive
      name
      shortcode
    }
    errors {
      key
      message
    }
  }
}
