fragment OrganizationFields on OrganizationResult {
  organization {
    id
    name
    display_name
    contact_name
    email
    provider_key
    provider_number 
   
    provider {
      id
      name
      url
      api_end_point   
    }
  }
}

fragment ErrorFields on OrganizationResult {
  errors {
    key
    message
  }
}