fragment OrganizationFields on OrganizationResult {
  organization {
    id
    name
    display_name
    contact {
      name
    }
    email
    provider_key
    provider_phone
    provider {
      id
      name
      url
      api_end_point
    }

    out_of_office {
      enabled
      start_time
      end_time
      flow_id
      enabled_days {
        id
        enabled
      }
    }
  }
}

fragment ErrorFields on OrganizationResult {
  errors {
    key
    message
  }
}