fragment OrganizationFields on OrganizationResult {
  organization {
    id
    name
    shortcode
    contact {
      name
    }
    email
    provider_appname
    provider_phone
    provider {
      id
      name
      shortcode
      keys
      secrets
    }

    out_of_office {
      enabled
      start_time
      end_time
      flow_id
      enabled_days {
        id
        enabled
      }
    }

    isActive
    timezone

    default_language {
      id
      label
    }

    active_languages {
      id
      label
    }
  }
}

fragment ErrorFields on OrganizationResult {
  errors {
    key
    message
  }
}