query organizationServices {
  organizationServices {
    google_cloud_storage
    dialogflow
    fun_with_flags
    bigquery
    ticketing_enabled
    roles_and_permission
    flow_uuid_display
    contact_profile_enabled
    auto_translation_enabled
    whatsapp_group_enabled
    certificate_enabled
    kaapi_enabled
    ask_me_bot_enabled
    whatsapp_forms_enabled
    unified_api_enabled
    errors {
      key
      message
    }
  }
}
