query organizationServices {
  organizationServices {
    google_cloud_storage
    dialogflow
    fun_with_flags
    bigquery
    ticketing_enabled
    roles_and_permission
    flow_uuid_display
    contact_profile_enabled
    auto_translation_enabled_for_open_ai
    auto_translation_enabled_for_google_trans
    errors {
      key
      message
    }
  }
}
