fragment SetupFields on SetupResult {
  organization {
    id
    name
    shortcode
    email
    isActive
    isApproved
  }
  contact {
    id
    name
    phone
  }
  credential
  is_valid
}

fragment ErrorFields on SetupResult {
  errors {
    key
    message
  }
}
