mutation updateOrganizationStatus($updateOrganizationId: ID!, $isActive: Boolean, $isApproved: Boolean) {
  updateOrganizationStatus(updateOrganizationId: $updateOrganizationId, isActive: $isActive, isApproved: $isApproved) {
    organization {
      email
      id
      isApproved
      isActive
      name
      shortcode
    }
    errors {
      key
      message
    }
  }
}
