fragment SheetFields on SheetResult {
    sheet {
        id
        label
        isActive
        url
        sheetDataCount
        syncStatus
        failureReason
    }
}

fragment ErrorFields on SheetResult {
    errors {
        key
        message
    }
}
