mutation updateGroupContacts($input:GroupContactsInput!) {
  updateGroupContacts(input: $input) {
    groupContacts {
      id
      contact {
        id
        name
      }
      group {
        id
        label
      }
    }
    numberDeleted
  }
}