fragment ProfileFields on ProfileResult {
  profile {
    id
    name
    type
    fields
    contact {
      id
      language {
        label
      }
    }
  }
}

fragment ErrorFields on ProfileResult {
  errors {
    key
    message
  }
}
