fragment ProfileFields on ProfileResult {
  profile {
    id
    name
    profile_type
    profile_registration_fields
    contact_profile_fields
  }
}

fragment ErrorFields on ProfileResult {
  errors {
    key
    message
  }
}