mutation createBillingSubscription($StripePaymentMethodId: String, $couponCode: String, $billingPeriod: String) {
  createBillingSubscription(StripePaymentMethodId: $StripePaymentMethodId, couponCode: $couponCode, billingPeriod: $billingPeriod) {
    subscription
    errors
  }
}