mutation updatePaymentMethod($StripePaymentMethodId: String!) {
  updatePaymentMethod(StripePaymentMethodId: $StripePaymentMethodId) {
    billing {
      currency
      email
      isActive
      StripePaymentMethodId
    }
    errors {
      key
      message
    }
  }
}