defmodule Glific.AI.CodecLiveTest do
  @moduledoc """
  The live-shape guard: proves a context rebuilt from stored rows is accepted by a real provider.

  Excluded from the default suite — these make paid network calls. Run deliberately:

      OPENAI_API_KEY=sk-... mix test --only eval_live

  Run this before bumping `req_llm` and before shipping a model change. `ReqLLM`'s structs are
  generated by `Zoi.Struct.struct_fields/1`, so a minor version can reshape them; the unit tests
  in `codec_test.exs` prove the codec round-trips against the structs *as they are today*, and
  only this test proves the result is still something a provider will accept.

  The failure this exists to catch is delayed by one turn: a message writes successfully and the
  error surfaces the next time the conversation continues, with nothing wrong at the write site.
  """

  use ExUnit.Case, async: false

  @moduletag :eval_live

  alias Glific.AI.Codec
  alias ReqLLM.Context
  alias ReqLLM.Generation
  alias ReqLLM.Response

  @model System.get_env("EVAL_LIVE_MODEL", "openai:gpt-4o")

  setup_all do
    case System.get_env("OPENAI_API_KEY") do
      nil -> raise "OPENAI_API_KEY must be set to run :eval_live tests"
      "" -> raise "OPENAI_API_KEY is empty"
      _key -> :ok
    end

    {:ok, _apps} = Application.ensure_all_started(:req_llm)
    :ok
  end

  test "a context rebuilt from stored rows is accepted by the provider on the next turn" do
    tool = query_tool()

    first_turn =
      Context.new([
        Context.system("You are a Glific support agent. Use tools to answer questions."),
        Context.user("Why is contact 42 stuck? Look at flow_contexts.")
      ])

    assert {:ok, %Response{} = response} =
             Generation.generate_text(@model, first_turn, tools: [tool], temperature: 0.0)

    calls = Response.tool_calls(response)
    assert calls != [], "model returned no tool call; cannot exercise the tool-call round trip"
    [call | _rest] = calls

    # Normalise on the way in, exactly as the runtime does, so the in-memory form is the one
    # storage returns.
    originals =
      (first_turn.messages ++
         [response.message, Context.tool_result(call.id, tool_payload())])
      |> Enum.map(&Codec.normalize/1)

    rebuilt = Enum.map(originals, &through_storage/1)

    assert rebuilt == originals,
           "messages changed shape crossing storage — the codec has drifted from ReqLLM's structs"

    assert {:ok, %Response{} = second} =
             Generation.generate_text(@model, Context.new(rebuilt),
               tools: [tool],
               temperature: 0.0
             )

    text = Response.text(second)

    assert is_binary(text) and text != "",
           "provider accepted the rebuilt context but returned nothing: #{inspect(second.finish_reason)}"
  end

  @spec through_storage(ReqLLM.Message.t()) :: ReqLLM.Message.t()
  defp through_storage(message) do
    {:ok, encoded} = Codec.encode(message)
    {:ok, decoded} = encoded |> Jason.encode!() |> Jason.decode!() |> Codec.decode()
    decoded
  end

  @spec query_tool() :: ReqLLM.Tool.t()
  defp query_tool do
    ReqLLM.Tool.new!(
      name: "query_org_data",
      description: "Read rows from a Glific table for the current organisation.",
      parameter_schema: [
        table: [type: :string, required: true, doc: "Table name, e.g. flow_contexts"],
        limit: [type: :pos_integer, doc: "Maximum rows to return"]
      ],
      callback: fn _args -> {:ok, tool_payload()} end
    )
  end

  @spec tool_payload() :: String.t()
  defp tool_payload, do: ~s({"rows":[{"contact_id":42,"node":"webhook"}]})
end
