fragment TemplateRephraseFields on TemplateRephraseResult {
  templateRephrase {
    id
    status
    rephrasedText
    errorMessage
    originalText
    action
  }
}

fragment ErrorFields on TemplateRephraseResult {
  errors {
    key
    message
  }
}
