name: Remove all labels on merge

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [closed]

jobs:
  remove-labels:
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Remove all labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ join(github.event.pull_request.labels.*.name, ',') }}
