mutation updateTemplateTags($input:TemplateTagsInput!) {
  updateTemplateTags(input: $input) {
    templateTags {
      id
      template {
        id
        label
      }
      tag {
        id
        label
      }
    }
    numberDeleted
  }
}